parameters:
  containerRuntime: ''
  skuPrefix: ''

jobs:
- job: create_marketplace_sku_${{ parameters.skuPrefix }}
  pool:
    name: $(BUILD_POOL)
  steps:
  - script: |
      docker run --rm \
      -v ${PWD}:/go/src/github.com/Azure/aks-engine \
      -w /go/src/github.com/Azure/aks-engine \
      ${DEIS_GO_DEV_IMAGE} make bootstrap
    displayName: Update tools
  - script: |
      docker run --rm \
      -v ${PWD}:/go/src/github.com/Azure/aks-engine \
      -w /go/src/github.com/Azure/aks-engine \
      -e AZURE_TENANT_ID=${AZURE_TENANT_ID} \
      -e AZURE_CLIENT_ID=${AZURE_CLIENT_ID} \
      -e AZURE_CLIENT_SECRET="$(AZURE_CLIENT_SECRET)" \
      -e SKU_PREFIX=${{ parameters.skuPrefix }} \
      -e SKU_TEMPLATE_FILE=${SKU_TEMPLATE_FILE} \
      -e PUBLISHER=${PUBLISHER} \
      -e OFFER=${OFFER} \
      -e CONTAINER_RUNTIME=${{ parameters.containerRuntime }} \
      ${DEIS_GO_DEV_IMAGE} ./vhd/publishing/new-windows-sku.sh
    displayName: Create a new marketplace SKU
  - task: PublishPipelineArtifact@1
    inputs:
      artifact: 'sku_info_${{ parameters.skuPrefix }}'
      path: 'sku-publishing-info.json'
  - script: |
      docker run --rm \
      -v ${PWD}:/go/src/github.com/Azure/aks-engine \
      -w /go/src/github.com/Azure/aks-engine \
      ${DEIS_GO_DEV_IMAGE} make tools-clean
    displayName: cleanup - clean hack/tools/bin
    condition: always()

